[package]
name = "fast_spheres_app"
version = "0.1.0"
edition = "2021"

[dependencies]
fast_spheres_core = { path = "../fast_spheres_core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
